invite=['Ayesha','Kainat','Anam']
print(invite[0])
print(invite[1])
print(invite[-1])
message=("\tI would like to invite you on dinner ")
print(invite[0]+message)
print(invite[-2]+message)
print(invite[2]+message)
message1=(invite[0]+"can't attend the dinner")
print(message1)
invite[0]='Sadia'
print(invite)
invite.insert(0,'Harram')
invite.insert(2,'Nimra')
invite.append('aqsa')
print(invite)
message2=('i invite only 2 persons')
print(message2)
a=("sorry we cant invite "+invite.pop(5))
print(a)
b=("sorry we cant invite "+invite.pop(3))
print(b)
c=("sorry we cant invite "+invite.pop(2))
print(c)
d=("sorry we cant invite "+invite.pop(0))
print(d)
print(invite)
print(invite)
del invite[1]
del invite[0]
g=("the dinner table is empty")
print( invite)
print(g)
